### ISSUE TITLE
Upgrade to v4 elastic agents api

### ISSUE THREAD

**Issue by tomzo** [gocd-contrib/openstack-elastic-agent#18]
By March 2019 we should add V4 API support - see https://www.gocd.org/releases/#18-10-0

The new API notifies about job completion. The question is - do we want to use that to e.g. remove agent? Otherwise we can just handle the request with no-op.

**Comment by chrislovsund** [comment]
At the moment we are using long running agents as the default. 
- It takes some time for them to register.
- Reusing agents speed up the pipeline for us. 
I have thought about adding the possibility to set TTL per profile also. Then we can have a long running profile. 
I vote for no-op for now. 
I rather spend time on feeding back errors to the Server’s notifications.

**Comment by chrislovsund** [comment]
Ok, I have started looking at it. Found some good info in https://github.com/gocd/gocd/issues/5191.
Will you merge https://github.com/gocd-contrib/openstack-elastic-agent/pull/19 soon? I guess you don't have to, but looks like some merge conflict might happen.

**Comment by ketan** [comment]
Good to close?

**Comment by tomzo** [comment]
yes, since 0.13.0 there is a v4 implementation - https://github.com/gocd-contrib/openstack-elastic-agent/blob/master/CHANGELOG.md#0130
