### ISSUE TITLE
 Upgrade to v5 elastic agents api

### ISSUE THREAD

**Issue by ketan** [gocd-contrib/openstack-elastic-agent#30]
See https://github.com/gocd/gocd/issues/5937. V5 adds support for multiple clusters. We hope to get the v5 support in by 19.3 (or 19.4, if we don't get time).

The idea is that an elastic profile will be associated with a cluster configuration (which is another key-value store, very much like an elastic profile).

You maybe able to follow the changes here: https://github.com/gocd-contrib/docker-elastic-agents/commits/master, or ask on the usual communication channels if you have questions/feedback.

/cc @GaneshSPatil

**Comment by GaneshSPatil** [comment]
\cc: @tomzo  @chrislovsund

**Comment by tomzo** [comment]
I don't see any problem with this. Once support in GoCD is released we'll update the openstack elastic profile to include cluster config.

**Comment by chrislovsund** [comment]
I have started looking at this. 
@tomzo can you please accept PR for #44 before I create a new PR for this issue.

**Comment by chrislovsund** [comment]
We have been running in production for a week now, without any problems. 
@tomzo it should be ok to merge PR unless you have any issues with PR.
