### ISSUE TITLE
Any suggestion on how to inject Environments into openstack instance?

### ISSUE THREAD

**Issue by chrislovsund** [gocd-contrib/openstack-elastic-agent#4]
Has anyone a suggestion on how to set Environments for the OpenStack go-agent?
Looking at https://github.com/gocd-contrib/docker-swarm-elastic-agents#using-your-own-docker-image-with-elastic-agents it looks as it is possible to set some values in the profile that is later used for a specific image by setting `agent.auto.register.environments=${GO_EA_AUTO_REGISTER_ENVIRONMENT}`

Or can that be easily added to cloud-init by setting `openstack_userdata` field?

**Comment by tomzo** [comment]
It would have to be handled just like the auto-registration key.
Plugin sets it in the metadata of VM  which is then read by [cloud-init script which sets the ID to autoregister.properties file](https://github.com/gocd-contrib/openstack-elastic-agent-tools/blob/master/cloudinit/cc_openstack_gocd.py#L56).
BTW it looks that environment is already on the [CreateAgentRequest](https://github.com/gocd-contrib/openstack-elastic-agent/blob/master/src/main/java/cd/go/contrib/elasticagents/openstack/requests/CreateAgentRequest.java#L37) class, so perhaps this was not implemented fully.
