### ISSUE TITLE
Plugin should allow the use of previous image IDs when assigning work

### ISSUE THREAD

**Issue by chrislovsund** [gocd-contrib/openstack-elastic-agent#9]
We have a problem when the image of "ExampleImageName" has been just rebuilt in OpenStack, that the jobs need to wait for new agents to be started and the old to slowly disappear. That usually results in a pileup in the GoCD jobs queue. 

We have updated the code to allow the use of the previous image ID as a fallback when assigning work, but not creating new agents.

**Comment by tomzo** [comment]
@chrislovsund Thank you for your work. I have merged it and released as 0.9.0
